### ISSUE TITLE
More instructions for installing

### ISSUE THREAD

**Issue by raphaelchinchilla** [LyzardKing/grive-indicator#7] opened 2019-07-07 18:13 UTC
Hi,

Can you give more instructions on how to install the indicator? I have installed the dependencies and cloned the repository, but the rest is really not clear from the instructions on the read me on how to install the indicator and make it run

**Comment by LyzardKing** [comment] 2019-07-07 18:40
Hi. That's right, some instructions are missing...
You can either install the snap (it's not in the store atm, so you should build it..)
or you can run
```
cd <source folder>
bin/grive-indicator
```

To install you can also use the setup.py by running
```
cd <source folder>
python3 setup.py install --record files.txt
```
(The record function creates a list of the files it installed in the system, so you can then remove them)
I would run it as a snap or with the first method described here, without running the install.
I'm thinking of releasing the snap in the store, if you're interested. So if you use the bin/grive-indicator method you can then transition to the snap once it's released

**Comment by raphaelchinchilla** [comment] 2019-07-07 22:37
Thanks! Your app is very nice! 

I don't plan on installing it, I like to keep my machine as clean as possible. One of those things that linux is much better than windows!

I also have a couple of improvements suggestions:

1) Change the icon when the sync is running
2) grive2 5.0 allows auto sync, you could probably implement it in the grive indicator
3) a GUI to see grive log in order to see if there were any problem in the sync

On the settings:

1) Explain what is the timmer unit
2) What is CSD?
3) Does it run grive with the option --new-rev?

**Comment by LyzardKing** [comment] 2019-07-12 10:24
suggestions:
1. an icon would be  nice, if someone wants to send me that ;)
2. I noticed the autosync, would be nice, I have no idea how to add it properly atm
3. the log can be done...I'll look into that soon

settings:
1. timer I guess...it's the interval between sync actions.
2. CSD (client side decorations), to integrate it better with gnome...but it'll be removed soon. it was mostly a test
3. new-rev? what's that option?

**Comment by raphaelchinchilla** [comment] 2019-07-12 17:27
hi =D
suggestions:
1) for the icon, I found some online. It is under CC, so you can use it as long as you reference the creator
https://www.iconfinder.com/icons/27883/refresh_sync_synchronize_icon
2) Great! Because the one for grive is kind of hermetic 
3) Great too!

setting:
1) I meant, what is the time unit? minutes, seconds, hours ...
2) gotcha
3) when syncing with grive, one can run grive --new-rev and if there has been a modification on the files, instead of erasing the old one, grive will run it as a new version. It is weird that this is not the default configuration, but this is what the google drive app on windows/mac does, or even if you simply upload a file on the web...

**Comment by LyzardKing** [comment] 2019-07-13 13:15
The time unit is in minutes... I'll add it in the UI if it's not there.
I'm not sure of the new rev...
If I change a file I want to change THAT file, not another one..
But one thing I can do is add a field where you can add custom grive options

On 12 July 2019 19:27:16 CEST, raphaelchinchilla <notifications@github.com> wrote:
>hi =D
>suggestions:
>1) for the icon, I found some online. It is under CC, so you can use it
>as long as you reference the creator
>https://www.iconfinder.com/icons/27883/refresh_sync_synchronize_icon
>2) Great! Because the one for grive is kind of hermetic 
>3) Great too!
>
>setting:
>1) I meant, what is the time unit? minutes, seconds, hours ...
>2) gotcha
>3) when syncing with grive, one can run grive --new-rev and if there
>has been a modification on the files, instead of erasing the old one,
>grive will run it as a new version. It is weird that this is not the
>default configuration, but this is what the google drive app on
>windows/mac does, or even if you simply upload a file on the web...
>
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/LyzardKing/grive-indicator/issues/7#issuecomment-510967886

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by raphaelchinchilla** [comment] 2019-07-16 00:06
It does change the new file, it just keeps the old one for 30 or 100 versions. There is more details about it in https://support.google.com/drive/answer/2409045?co=GENIE.Platform%3DDesktop&hl=en

**Comment by zjsr** [comment] 2019-09-27 17:09
Thank you for your work on grive-indicator.

I have 2 computers using grive2 (previously installed) to synchronize with different Google Drive accounts.

On Computer 1, I downloaded grive-indicator-master.zip , extracted the files into a "New" folder in the /home directory and ran the bin/grive-indicator in the "bin" subfolder.   Although I have not tried the "ignore" function, all has gone well on Computer 1 over the last few weeks.

On Computer 2. I wanted to install grive-indicator in a more secure fashion.  Not knowing how to use SNAP, I elected to install via the terminal "python3 setup.py install --record files.txt" command. While the program files were installed in the /usr/share/applications , /usr/share/icons/~ ,   /usr/local/lib/python3.6/dist-packages directories, and the "files.txt" created, upon execution grive-indicator-0.2 opens.   Not good.  I have subsequently extracted the grive-indicator-master.zip files and tried to use these in the Computer 2 /home directory (as on Computer 1).  However, whenever using, the grive-indicator0.2 still opens. 

Can you advise if there is a single file/folder yjat was installed in the Computer 2 /usr directory that I can remove or easily replace which will allow grive-indicator version 19.06 to operate on Computer 2?

Thank you for any assistance you can provide.

**Comment by LyzardKing** [comment] 2019-09-28 19:50
@zjsr I can't reproduce, if I install the script in /usr bin is grive-indicator.
Could the repo not be up to date in computer 2?
My suggestion is to try and remove the install, with every file it left on the system.
Then pull the latest version and try again.

**Comment by zjsr** [comment] 2019-10-02 01:04
Thank you for your prompt attention.  I am sure the error was caused by me. 
I have removed all the Computer 2 files in files.txt I also removed all files which include "grive-indicator" .  While I did this, I noticed I had downloaded "grive-indicator-0.2.zip" as well as "grive-indicator-master.zip ".  It appears both version 1.0 and version 19.06 were installed.
After the Computer 2 files were removed, I redownloaded "grive-indicator-master.zip", unpacked the zip and tried simply to run"
cd <source folder>
bin/grive-indicator
in the terminal.   This resulted in a shadow icon in the task bar, and a number of error messages in the terminal window.  The shadow icon did not permit access to the preferences settings.png and did not sync with Google Drive.  FYI, the attached file provides the terminal window output modified to conceal the username.  

[grive_indicator_Terminal_Errors.txt](https://github.com/LyzardKing/grive-indicator/files/3679040/grive_indicator_Terminal_Errors.txt)

It seems to me that there could be at one or more files from prior usage that need to be removed (or that I removed one or more files needed from prior use).
Since the "grive" command in grive2 still synchronizes with Google Drive, I continue to use that.  Please let me know if you have any further suggestionsto get the 19.06 version of grive-indicator to work on Computer 2.  
Thanks again.

**Comment by LyzardKing** [comment] 2019-10-03 06:32
The first error I see is 
"ERROR: Missing grive in PATH", which says that grive is not able to be found in PATH. How do you access it? Is it installed in a non standard way?
your folder "/home/~/JSRGoogleDrive" does not seem to exist
Is there a file in /home/$USER/.confg/grive_indicator.conf? And what are its contents? 

They should be something like this:
[DEFAULT]
dark = true
time = 30
revisions = true
folder = /home/your username/JSRGoogleDrive
upload_speed = 0
download_speed = 0
show_notifications = false

**Comment by LyzardKing** [comment] 2019-10-03 13:59
@zjsr Just out of curiosity, and if I were to build non snap packages...
what distros are you running?

**Comment by zjsr** [comment] 2019-10-03 19:39
1.  I think grive is installed in normal fashion 
I have a folder "/usr/lib/grive" containing file "grive-sync.sh" and a folder "/usr/share/doc/grive" containing a file "changelog.debian.gz" and a file "copyright" .  Grive is activated in Terminal via:
UserName@ATR-Dell755SFF:-$ "cd /home/UserName/JSRGoogleDrive"
UserName@ATR-Dell755SFF:~/JSRGoogleDrive $ "grive"

2. Folder "/home/"username"/JSRGoogleDrive" is present.

3. Folder "/home/$USER/.confg/grive_indicator.conf" not found. The folder or file "/usr/local/lib/python3.6/dist-packages/grive_indicator-19.6-py3.6.egg/grive_indicator/data/grive_indicator.conf" deleted when removing files in files.txt"

Regarding your Snap query, Computer 2 is using Linux Mint 19.1, Cinnamon version, based on Ubuntu 18.04 LTS.

Thanks again for your assistance.

**Comment by LyzardKing** [comment] 2019-10-03 19:47
What happens if you run with --debug?

**Comment by zjsr** [comment] 2019-10-04 16:40
Not sure what you wanted, bur in Terminal, I ran
"cd /home/UserName/JSRGoogleDrive"
$ grive --debug

Output
"
config file name "./.grive"
HTTP POST "https://accounts.google.com/o/oauth2/token"
HTTP response 200
Reading local directories
file .trash is ignored by grive
file .grive is ignored by grive
file .grive_state is ignored by grive
Reading remote server file list
HTTP GET "https://www.googleapis.com/drive/v2/files?maxResults=999999999&q=trashed%3dfalse"
"
then information on lots of individual files

Hope that helps.

**Comment by LyzardKing** [comment] 2019-10-04 16:43
Actually I need the log for grive-indicator ;)
so bin/grive-indicator --debug

**Comment by zjsr** [comment] 2019-10-04 19:54
On Computer 2
~/grive-indicator-master$ bin/grive-indicator --debug 
(grive-indicator:1171): Gtk-WARNING **: 14:47:01.087: Can't set a parent on widget which has a parent

(grive-indicator:1171): Gtk-WARNING **: 14:47:01.087: Can't set a parent on widget which has a parent
DEBUG: Running in debug mode
DEBUG: Emulate sync, then update label
DEBUG: Running: ['grive', '--upload-speed ', '--download-speed ']
DEBUG: Grive log: Options are incorrect. Use -h for help
DEBUG: Finished sync

(grive-indicator:1171): Gdk-CRITICAL **: 14:47:01.505: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed

On Computer 1
~/grive-indicator-master$ bin/grive-indicator --debug

(grive-indicator:21088): Gtk-WARNING **: 14:16:57.973: Can't set a parent on widget which has a parent

(grive-indicator:21088): Gtk-WARNING **: 14:16:57.973: Can't set a parent on widget which has a parent
INFO: Revisions active
DEBUG: Running in debug mode
DEBUG: Emulate sync, then update label
DEBUG: Running: ['grive', '--new-rev']
DEBUG: Grive log: Reading local directories
DEBUG: Grive log: Reading remote server file list
DEBUG: Grive log: Synchronizing files
many files

**Comment by LyzardKing** [comment] 2019-10-04 21:42
Computer 2 should have created the config file...
It can't seem to get the right settings without it.
I'm not sure what the issue is.
Try (but I'm guessing here..) copying the config file from https://raw.githubusercontent.com/LyzardKing/grive-indicator/master/grive_indicator/data/grive_indicator.conf to /home/$USER/.config/grive_indicator.conf
Remember to set the folder (the gui should ask you to set it)
Hopefully it'll read those settings

**Comment by zjsr** [comment] 2019-10-09 02:49
Thanks for all the advice.
In the end, I deleted the user account on Computer 2.
When I recreated the user account on Computer 2, using grive-indicator-master as source and bin/grive-indicator worked fine.

**Comment by LyzardKing** [comment] 2019-10-09 07:47
Ok. Glad it worked in the end.
Closing for now

**Closed as completed by LyzardKing** 2019-10-09 07:47 UTC
